import {
  createAgency,
  createAttachment,
  createCace,
  createContract,
  createContractType,
  createDepartment,
  createDrivingAuthorization,
  createEmployee,
  createMedia,
  createMedicalVisit,
  createNote,
  createOnlineTraining,
  createPosition,
  createPost,
  createWorkLocation,
  deleteAgency,
  deleteAttachment,
  deleteCace,
  deleteContract,
  deleteContractType,
  deleteDepartment,
  deleteDrivingAuthorization,
  deleteEmployee,
  deleteExportFromHistory,
  deleteMedia,
  deleteMedicalVisit,
  deleteNote,
  deleteOnlineTraining,
  deletePosition,
  deleteWorkLocation,
  downloadAttachment,
  downloadMedia,
  exportData,
  getActiveContractByEmployee,
  getAgencies,
  getAlerts,
  getAllDrivingAuthorizationStatuses,
  getAllMedia,
  getAttachmentById,
  getAttachments,
  getAttachmentsByEmployee,
  getAttachmentsByEntity,
  getAttachmentsByType,
  getCaces,
  getCacesByEmployee,
  getContracts,
  getContractsByEmployee,
  getContractTypes,
  getDeletedAgencies,
  getDeletedContractTypes,
  getDeletedDepartments,
  getDeletedEmployees,
  getDeletedPositions,
  getDeletedWorkLocations,
  getDepartments,
  getDrivingAuthorizationStatus,
  getDrivingAuthorizations,
  getDrivingAuthorizationsByEmployee,
  getEmployeeById,
  getEmployees,
  // Export history handlers
  getExportHistory,
  getMediaById,
  getMedicalVisits,
  getMedicalVisitsByEmployee,
  getNotes,
  getOnlineTrainings,
  getOnlineTrainingsByEmployee,
  getPositions,
  getPosts,
  getSettings,
  getWorkLocations,
  migrateAddNotesTable,
  openExportedFile,
  openExportFolder,
  permanentDeleteAgency,
  permanentDeleteContractType,
  permanentDeleteDepartment,
  permanentDeleteEmployee,
  permanentDeletePosition,
  permanentDeleteWorkLocation,
  // Export handlers
  previewExport,
  restoreAgency,
  restoreContractType,
  restoreDepartment,
  restoreEmployee,
  restorePosition,
  restoreWorkLocation,
  updateAgency,
  updateCace,
  updateContract,
  updateContractType,
  updateDepartment,
  updateDrivingAuthorization,
  updateEmployee,
  updateMedicalVisit,
  updateNote,
  updateOnlineTraining,
  updatePosition,
  updateSettings,
  updateWorkLocation,
} from "./handlers";

export const database = {
  getPosts,
  createPost,
  getPositions,
  createPosition,
  updatePosition,
  deletePosition,
  getWorkLocations,
  createWorkLocation,
  updateWorkLocation,
  deleteWorkLocation,
  getEmployees,
  getEmployeeById,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getContracts,
  getContractsByEmployee,
  getActiveContractByEmployee,
  createContract,
  updateContract,
  deleteContract,
  // Media
  getAllMedia,
  getMediaById,
  createMedia,
  deleteMedia,
  downloadMedia,
  // Attachments
  getAttachments,
  getAttachmentById,
  getAttachmentsByEntity,
  getAttachmentsByType,
  getAttachmentsByEmployee,
  createAttachment,
  deleteAttachment,
  downloadAttachment,
  // Departments
  getDepartments,
  createDepartment,
  updateDepartment,
  deleteDepartment,
  // Agencies
  getAgencies,
  createAgency,
  updateAgency,
  deleteAgency,
  // Contract Types
  getContractTypes,
  createContractType,
  updateContractType,
  deleteContractType,
  // CACES
  getCaces,
  getCacesByEmployee,
  createCace,
  updateCace,
  deleteCace,
  // Medical Visits
  getMedicalVisits,
  getMedicalVisitsByEmployee,
  createMedicalVisit,
  updateMedicalVisit,
  deleteMedicalVisit,
  // Driving Authorizations
  getDrivingAuthorizations,
  getDrivingAuthorizationsByEmployee,
  getDrivingAuthorizationStatus,
  getAllDrivingAuthorizationStatuses,
  createDrivingAuthorization,
  updateDrivingAuthorization,
  deleteDrivingAuthorization,
  // Online Trainings
  getOnlineTrainings,
  getOnlineTrainingsByEmployee,
  createOnlineTraining,
  updateOnlineTraining,
  deleteOnlineTraining,
  // Settings
  getSettings,
  updateSettings,
  // Notes
  migrateAddNotesTable,
  getNotes,
  createNote,
  updateNote,
  deleteNote,
  // Alerts
  getAlerts,
  // Trash / Restore
  getDeletedEmployees,
  restoreEmployee,
  permanentDeleteEmployee,
  getDeletedPositions,
  restorePosition,
  permanentDeletePosition,
  getDeletedWorkLocations,
  restoreWorkLocation,
  permanentDeleteWorkLocation,
  getDeletedDepartments,
  restoreDepartment,
  permanentDeleteDepartment,
  // Agencies
  getDeletedAgencies,
  restoreAgency,
  permanentDeleteAgency,
  getDeletedContractTypes,
  restoreContractType,
  permanentDeleteContractType,
  // Export
  previewExport,
  exportData,
  openExportedFile,
  openExportFolder,
  // Export history
  getExportHistory,
  deleteExportFromHistory,
};
