import {
  createContract,
  createContractType,
  createDepartment,
  createEmployee,
  createPosition,
  createPost,
  createWorkLocation,
  deleteContract,
  deleteContractType,
  deleteDepartment,
  deleteEmployee,
  deletePosition,
  deleteWorkLocation,
  getActiveContractByEmployee,
  getContracts,
  getContractsByEmployee,
  getContractTypes,
  getDepartments,
  getEmployeeById,
  getEmployees,
  getPositions,
  getPosts,
  getWorkLocations,
  updateContract,
  updateContractType,
  updateDepartment,
  updateEmployee,
  updatePosition,
  updateWorkLocation,
} from "./handlers";

export const database = {
  getPosts,
  createPost,
  getPositions,
  createPosition,
  updatePosition,
  deletePosition,
  getWorkLocations,
  createWorkLocation,
  updateWorkLocation,
  deleteWorkLocation,
  getEmployees,
  getEmployeeById,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getContracts,
  getContractsByEmployee,
  getActiveContractByEmployee,
  createContract,
  updateContract,
  deleteContract,
  // Departments
  getDepartments,
  createDepartment,
  updateDepartment,
  deleteDepartment,
  // Contract Types
  getContractTypes,
  createContractType,
  updateContractType,
  deleteContractType,
};
