import { createPost, getPosts, getPositions, createPosition, updatePosition, deletePosition, getWorkLocations, createWorkLocation, updateWorkLocation, deleteWorkLocation, getEmployees, getEmployeeById, createEmployee, updateEmployee, deleteEmployee, getContracts, getContractsByEmployee, getActiveContractByEmployee, createContract, updateContract, deleteContract } from "./handlers";

export const database = {
  getPosts,
  createPost,
  getPositions,
  createPosition,
  updatePosition,
  deletePosition,
  getWorkLocations,
  createWorkLocation,
  updateWorkLocation,
  deleteWorkLocation,
  getEmployees,
  getEmployeeById,
  createEmployee,
  updateEmployee,
  deleteEmployee,
  getContracts,
  getContractsByEmployee,
  getActiveContractByEmployee,
  createContract,
  updateContract,
  deleteContract,
};
