import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

const COLORS = [
  { name: "Cyan", value: "bg-cyan-500" },
  { name: "Amber", value: "bg-amber-500" },
  { name: "Violet", value: "bg-violet-500" },
  { name: "Emerald", value: "bg-emerald-500" },
  { name: "Rose", value: "bg-rose-500" },
  { name: "Blue", value: "bg-blue-500" },
  { name: "Green", value: "bg-green-500" },
  { name: "Red", value: "bg-red-500" },
  { name: "Orange", value: "bg-orange-500" },
  { name: "Indigo", value: "bg-indigo-500" },
];

function generateCode(name: string): string {
  return (
    "SITE_" +
    name
      .toUpperCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^A-Z0-9]/g, "_")
  );
}

interface WorkLocation {
  id: number;
  code: string;
  name: string;
  color: string;
  isActive: boolean;
}

interface EditWorkLocationDialogProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  onUpdate?: (data: {
    code: string;
    name: string;
    color: string;
    isActive: boolean;
  }) => void;
  location?: WorkLocation | null;
}

export function EditWorkLocationDialog({
  open,
  onOpenChange,
  onUpdate,
  location,
}: EditWorkLocationDialogProps) {
  const { t } = useTranslation();
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [selectedColor, setSelectedColor] = useState(COLORS[0].value);
  const [isActive, setIsActive] = useState(true);

  // Auto-generate code when name changes
  useEffect(() => {
    if (name.trim()) {
      setCode(generateCode(name));
    }
  }, [name]);

  useEffect(() => {
    if (location) {
      setName(location.name);
      setCode(location.code);
      setSelectedColor(location.color);
      setIsActive(location.isActive);
    }
  }, [location]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!(name.trim() && code.trim())) {
      return;
    }

    onUpdate?.({
      code: code.trim(),
      name: name.trim(),
      color: selectedColor,
      isActive,
    });
  };

  const isFormValid = name.trim();

  return (
    <Dialog onOpenChange={onOpenChange} open={open}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("workLocations.editLocation")}</DialogTitle>
          <DialogDescription>
            {t("workLocations.editLocationDescription")}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="location-name">{t("workLocations.name")}</Label>
                <span className="text-muted-foreground text-xs">
                  {name.length}/30
                </span>
              </div>
              <Input
                id="location-name"
                maxLength={30}
                onChange={(e) => setName(e.target.value)}
                placeholder={t("workLocations.namePlaceholder")}
                value={name}
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="location-code">{t("workLocations.code")}</Label>
              <Input
                id="location-code"
                onChange={(e) => setCode(e.target.value)}
                placeholder={t("workLocations.codePlaceholder")}
                value={code}
              />
              <p className="text-muted-foreground text-xs">
                {t("workLocations.codeAutoGenerated")}
              </p>
            </div>
            <div className="grid gap-2">
              <Label>{t("workLocations.color")}</Label>
              <div className="flex flex-wrap gap-2">
                {COLORS.map((color) => (
                  <button
                    className={`h-8 w-8 rounded-md ${color.value} ${
                      selectedColor === color.value
                        ? "ring-2 ring-gray-900 ring-offset-2"
                        : ""
                    } transition-all hover:scale-110`}
                    key={color.value}
                    onClick={() => setSelectedColor(color.value)}
                    title={color.name}
                    type="button"
                  />
                ))}
              </div>
            </div>
            <div className="grid gap-2">
              <Label>{t("workLocations.status")}</Label>
              <div className="flex gap-4">
                <label className="flex cursor-pointer items-center gap-2">
                  <input
                    checked={isActive === true}
                    className="accent-green-600"
                    name="isActive"
                    onChange={() => setIsActive(true)}
                    type="radio"
                  />
                  <span className="text-sm">{t("workLocations.active")}</span>
                </label>
                <label className="flex cursor-pointer items-center gap-2">
                  <input
                    checked={isActive === false}
                    className="accent-gray-600"
                    name="isActive"
                    onChange={() => setIsActive(false)}
                    type="radio"
                  />
                  <span className="text-sm">{t("workLocations.inactive")}</span>
                </label>
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button
              onClick={() => onOpenChange?.(false)}
              type="button"
              variant="outline"
            >
              {t("common.cancel")}
            </Button>
            <Button disabled={!isFormValid} type="submit">
              {t("common.save")}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
