import { generateCode } from "@@/lib/utils";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

import { DEFAULT_COLOR } from "@/lib/colors";
import { ColorPicker } from "@/components/ui/color-picker";

interface Position {
  id: number;
  code: string;
  name: string;
  color: string;
  isActive: boolean;
}

interface EditPositionDialogProps {
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  onUpdate?: (data: {
    code: string;
    name: string;
    color: string;
    isActive: boolean;
  }) => void;
  position?: Position | null;
}

export function EditPositionDialog({
  open,
  onOpenChange,
  onUpdate,
  position,
}: EditPositionDialogProps) {
  const { t } = useTranslation();
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [selectedColor, setSelectedColor] = useState(DEFAULT_COLOR);
  const [isActive, setIsActive] = useState(true);

  // Auto-generate code when name changes
  useEffect(() => {
    if (name.trim()) {
      setCode(generateCode(name));
    }
  }, [name]);

  useEffect(() => {
    if (position) {
      setName(position.name);
      setCode(position.code);
      setSelectedColor(position.color);
      setIsActive(position.isActive);
    }
  }, [position]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!(name.trim() && code.trim())) {
      return;
    }

    onUpdate?.({
      code: code.trim(),
      name: name.trim(),
      color: selectedColor,
      isActive,
    });
  };

  const isFormValid = name.trim();

  return (
    <Dialog onOpenChange={onOpenChange} open={open}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{t("positions.editPosition")}</DialogTitle>
          <DialogDescription>
            {t("positions.editPositionDescription")}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <div className="flex items-center justify-between">
                <Label htmlFor="position-name">{t("positions.name")}</Label>
                <span className="text-muted-foreground text-xs">
                  {name.length}/30
                </span>
              </div>
              <Input
                id="position-name"
                maxLength={30}
                onChange={(e) => setName(e.target.value)}
                placeholder={t("positions.namePlaceholder")}
                value={name}
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="position-code">{t("positions.code")}</Label>
              <Input
                id="position-code"
                onChange={(e) => setCode(e.target.value)}
                placeholder={t("positions.codePlaceholder")}
                value={code}
              />
              <p className="text-muted-foreground text-xs">
                {t("positions.codeAutoGenerated")}
              </p>
            </div>
            <div className="grid gap-2">
              <Label>{t("positions.color")}</Label>
              <ColorPicker value={selectedColor} onChange={setSelectedColor} />
            </div>
            <div className="grid gap-2">
              <Label>{t("positions.status")}</Label>
              <div className="flex gap-4">
                <label className="flex cursor-pointer items-center gap-2">
                  <input
                    checked={isActive === true}
                    className="accent-green-600"
                    name="isActive"
                    onChange={() => setIsActive(true)}
                    type="radio"
                  />
                  <span className="text-sm">{t("positions.active")}</span>
                </label>
                <label className="flex cursor-pointer items-center gap-2">
                  <input
                    checked={isActive === false}
                    className="accent-gray-600"
                    name="isActive"
                    onChange={() => setIsActive(false)}
                    type="radio"
                  />
                  <span className="text-sm">{t("positions.inactive")}</span>
                </label>
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button
              onClick={() => onOpenChange?.(false)}
              type="button"
              variant="outline"
            >
              {t("common.cancel")}
            </Button>
            <Button disabled={!isFormValid} type="submit">
              {t("common.save")}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
